# Generated by Django 3.1.7 on 2021-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='courses', max_length=500)),
                ('slug1', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
