# Generated by Django 3.1.7 on 2021-04-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='slug1',
        ),
    ]
