# Generated by Django 3.1.7 on 2021-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_slug1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='', upload_to='courses/images'),
        ),
    ]
