# Generated by Django 3.1.7 on 2021-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210422_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
