# Generated by Django 3.2 on 2021-04-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courses_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='yearsOfCourse',
            field=models.IntegerField(default=3),
        ),
    ]
