# Generated by Django 3.2 on 2021-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courses_yearsofcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='courses/images'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
