# Generated by Django 3.1.7 on 2021-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210423_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdfs',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
