# Generated by Django 3.1.7 on 2021-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_pdfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdfs',
            field=models.FileField(default='', upload_to='pdfs'),
        ),
    ]
