# Generated by Django 3.2 on 2021-04-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_paper_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
