# Generated by Django 3.1.7 on 2021-04-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
