# Generated by Django 3.2 on 2021-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_paper_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
