# Generated by Django 3.1.7 on 2021-04-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20210425_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='semester',
            new_name='paper_name',
        ),
    ]
