# Generated by Django 3.1.7 on 2021-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210425_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
