# Generated by Django 3.1.7 on 2021-04-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20210425_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='paperslug',
        ),
    ]
