# Generated by Django 3.1.7 on 2021-04-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_paper_paperslug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
