# Generated by Django 3.1.7 on 2021-04-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paperslug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
