# Generated by Django 3.1.7 on 2021-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_paper_paperslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='upload_paper',
            field=models.FileField(default='', upload_to='papers'),
        ),
    ]
