# Generated by Django 3.2 on 2021-04-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_year_upload_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='paperslug',
        ),
    ]
