# Generated by Django 3.2 on 2021-04-25 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='developer')),
                ('nick_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=100)),
                ('link', models.URLField(default='')),
                ('title', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='youtube')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verify', models.BooleanField(default=False)),
                ('autogen_otp', models.IntegerField()),
                ('university_roll', models.BigIntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(default='add mobile number', max_length=20)),
                ('college_name', models.CharField(default='Dr. B.C. Roy Engineering College - Durgapur', max_length=200)),
                ('state', models.CharField(default='West Bengal', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, upload_to='pofile_pics')),
                ('course', models.CharField(choices=[('bca', 'BCA'), ('bba', 'BBA'), ('btech-me', 'B.Tech. ME'), ('btech-ce', 'B.Tech. CE'), ('btech-ei', 'B.Tech. EI'), ('btech-ee', 'B.Tech. EE'), ('btech-ec', 'B.Tech. EC'), ('btech-it', 'B.Tech. IT'), ('btech-cs', 'B.Tech. CS'), ('mca', 'MCA'), ('mba', 'MBA')], default='BCA', max_length=10)),
                ('Semester', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'six'), (7, 'seven'), (8, 'eight')], default=1)),
                ('bio', models.CharField(default='update your bio.', max_length=500)),
                ('portfolio_site', models.URLField(blank=True, default='')),
                ('upload_cv', models.FileField(blank=True, upload_to='user_cvs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
