# Generated by Django 3.2 on 2021-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='protfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(default='update your bio.', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='college_name',
            field=models.CharField(default='Dr. B.C. Roy Engineering College - Durgapur', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True, default='portfolio website'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='state',
            field=models.CharField(default='West Bengal', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='upload_cv',
            field=models.FileField(blank=True, default='', upload_to='user_cvs'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(default='add mobile number', max_length=15),
        ),
    ]
