# Generated by Django 3.2 on 2021-04-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userprofileinfo_university_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_bcrecian',
            field=models.BooleanField(default=False),
        ),
    ]
