# Generated by Django 3.2 on 2021-04-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
