# Generated by Django 3.1.7 on 2021-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofileinfo_is_bcrecian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
