# Generated by Django 3.2 on 2021-04-22 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210423_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 23, 3, 47, 5, 235535)),
        ),
    ]
