# Generated by Django 3.2 on 2021-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(default='update your bio.🖊️', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(default='add mobile number 🖊️', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True, default='portfolio website🖊️'),
        ),
    ]
