# Generated by Django 3.2 on 2021-04-22 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 23, 3, 52, 23, 298846)),
        ),
    ]
