# Generated by Django 3.1.7 on 2021-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210426_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.TextField(default='Update Your Bio'),
        ),
    ]
