# Generated by Django 3.2 on 2021-04-22 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 23, 3, 59, 53, 693129)),
        ),
    ]
