# Generated by Django 3.2 on 2021-04-22 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210423_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 23, 4, 3, 32, 296635)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='color',
            field=models.CharField(choices=[('bca', 'BCA'), ('bba', 'BBA'), ('b.Tech. ME', 'B.Tech. ME'), ('b.Tech. CE', 'B.Tech. CE'), ('b.Tech. EI', 'B.Tech. EI'), ('b.Tech. EE', 'B.Tech. EE'), ('b.Tech. EC', 'B.Tech. EC'), ('b.Tech. IT', 'B.Tech. IT'), ('b.Tech. CS', 'B.Tech. CS'), ('mca', 'MCA'), ('mba', 'MBA')], default='BCA', max_length=10),
        ),
    ]
