# Generated by Django 3.2 on 2021-04-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210425_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='upload_cv',
            field=models.FileField(blank=True, upload_to='user_cvs'),
        ),
    ]
