# Generated by Django 3.2 on 2021-04-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210425_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Semester',
            field=models.CharField(choices=[(1, 1), (1, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, max_length=8),
        ),
    ]
