# Generated by Django 3.2 on 2021-04-22 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210423_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Course',
            new_name='course',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Semester',
            field=models.CharField(choices=[('first', 1), ('second', 2), ('third', 3), ('fourth', 4), ('fifth', 5), ('six', 6), ('seven', 7), ('eight', 8)], default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 23, 4, 7, 14, 580846)),
        ),
    ]
