# Generated by Django 3.2 on 2021-04-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_userprofileinfo_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Semester',
            field=models.CharField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'six'), (7, 'seven'), (8, 'eight')], default=1, max_length=8),
        ),
    ]
