# Generated by Django 3.1.7 on 2021-04-23 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210423_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dateTime',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 4, 23, 10, 53, 53, 994512)),
        ),
    ]
