# Generated by Django 3.2 on 2021-04-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_contact_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='dateTime',
        ),
    ]
