# Generated by Django 3.2 on 2021-04-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_userprofileinfo_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(default='add mobile number', max_length=20),
        ),
    ]
