# Generated by Django 3.2 on 2021-04-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='course',
            field=models.CharField(choices=[('bca', 'BCA'), ('bba', 'BBA'), ('btech-me', 'B.Tech. ME'), ('btech-ce', 'B.Tech. CE'), ('btech-ei', 'B.Tech. EI'), ('btech-ee', 'B.Tech. EE'), ('btech-ec', 'B.Tech. EC'), ('btech-it', 'B.Tech. IT'), ('btech-cs', 'B.Tech. CS'), ('mca', 'MCA'), ('mba', 'MBA')], default='BCA', max_length=10),
        ),
    ]
