# Generated by Django 3.1.7 on 2021-04-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_userprofileinfo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Semester',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'six'), (7, 'seven'), (8, 'eight')], default=1),
        ),
    ]
