# Generated by Django 3.1.7 on 2021-04-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210423_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='dateTime',
        ),
    ]
