# Generated by Django 3.2 on 2021-04-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210425_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
