# Generated by Django 3.2 on 2021-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_userprofileinfo_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='otp',
            field=models.IntegerField(blank=True),
        ),
    ]
