# Generated by Django 3.1.7 on 2021-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_youtubevideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='developer')),
                ('nick_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
