# Generated by Django 3.2 on 2021-04-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_userprofileinfo_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='otp',
            new_name='autogen_otp',
        ),
    ]
