# Generated by Django 3.2 on 2021-04-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
